
spark:
  app_name: Streaming Pipeline
  config: 
    spark.streaming.stopGracefullyOnShutdown: True
kafka:
  bootstrap_servers: &kafka_servers >-
    kafka-broker-1:19092,kafka-broker-2:19093,kafka-broker-3:19094
  topic: &kafka_topic books
  config: 
    kafka.bootstrap.servers: *kafka_servers
    subscribe: *kafka_topic
    includeHeaders: "true"
    startingOffsets: "earliest"
    failOnDataLoss: "false"
    maxOffsetsPerTrigger: 5
schema_registry:
  url: http://schema-registry:8081
  # SCHEMA_REGISTRY_SUBJECT: f"{KAFKA_TOPIC}-value"
postgres:
  user: postgres
  password: postgres
  db_name: postgres
  server: postgresdb  # '127.0.0.1'
  port: 5432
  #JDBC_URL = f"jdbc:postgresql://{SERVER}/{DB_NAME}"
  #TBL_NAME: f"public.{KAFKA_TOPIC}"

