[project]
name = "utils"
version = "0.1.0"
description = ""
authors = [
    {name = "RaymondOnn", email = "raymondonn@gmail.com"},
]
dependencies = []
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
